# This file was generated by GoReleaser. DO NOT EDIT.
class Badwolf < Formula
  desc "Hammer or Scapel"
  homepage "https://marcelo.correia.io"
  url "https://github.com/marcelocorreia/badwolf/marcelocorreia/badwolf/releases/download/0.0.15/badwolf-0.0.15-darwin-x86_64.tar.gz"
  version "0.0.15"
  sha256 "da73014f16242a2c2c8444bfbca62d16db44bba99cdaf47d8c3bc22dfb07b7aa"

  def install
    bin.install "badwolf"
  end

  test do
    system "#{bin}/badwolf --version"
  end
end
