# This file was generated by GoReleaser. DO NOT EDIT.
class Badwolf < Formula
  desc "Hammer or Scapel"
  homepage "https://marcelo.correia.io"
  url "https://github.com/marcelocorreia/badwolf/marcelocorreia/badwolf/releases/download/0.0.3/badwolf-0.0.3-darwin-x86_64.tar.gz"
  version "0.0.3"
  sha256 "c75264d0a549566cd6862d20c3adda661cfd91ad64c3b645aa8007b5b379bd48"

  def install
    bin.install "badwolf"
  end

  test do
    system "#{bin}/badwolf --version"
  end
end
