# This file was generated by GoReleaser. DO NOT EDIT.
class GoTemplateEngine < Formula
  desc "Go Template Engine (GTE) - Easy util to apply Go Templates in BAU jobs"
  homepage "https://marcelo.correia.io"
  url "https://github.com/marcelocorreia/go-template-engine/releases/download/3.3.9/go-template-engine-3.3.9-darwin-x86_64.tar.gz"
  version "3.3.9"
  sha256 "b5b64047c77595b8a936123dbbd7fa9ea0535407518ddfb300bc983345d99c37"

  def install
    bin.install "go-template-engine"
    bin.install_symlink libexec/"gte"
  end

  test do
    system "#{bin}/go-template-engine --version"
  end
end
