# This file was generated by GoReleaser. DO NOT EDIT.
class Hammer < Formula
  desc "Hammer or Scapel"
  homepage "https://marcelo.correia.io"
  url "https://github.com/marcelocorreia/hammer/marcelocorreia/hammer/releases/download/0.0.25/hammer-0.0.25-darwin-x86_64.tar.gz"
  version "0.0.25"
  sha256 "aafc3e395c8fd0cbd7d4335ede44eb9bbb99857a0aa5296a4c8ac8b0e7292923"

  def install
    bin.install "hammer"
    bin.install "hammer-minion"
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
      <dict>
        <key>KeepAlive</key>
        <dict>
          <key>SuccessfulExit</key>
          <false/>
        </dict>
        <key>Label</key>
        <string>#{plist_name}</string>
        <key>ProgramArguments</key>
        <array>
          <string>#{opt_bin}/hammer</string>
          <string>server</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>StandardErrorPath</key>
        <string>#{var}/log/hammer.log</string>
        <key>StandardOutPath</key>
        <string>#{var}/log/hammer.log</string>
      </dict>
    </plist>

  EOS
  end

  test do
    system "#{bin}/hammer --version"
  end
end
