---
resources:
  - name: git-repo-master
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}


  - name: docker_image
    type: docker-image
    source:
      repository: {{container_fullname}}
      email: {{docker_mail}}
      username: {{docker_user}}
      password: {{docker_password}}
      cache: true

  - name: resource_version
    type: semver
    source:
      driver: git
      initial_version: 0.0.1
      uri: {{git_repo_url}}
      branch: version
      file: version
      private_key: {{git_private_key}}
      username: {{github_user}}

jobs:
  - name: labs-core-apply
    serial: true
    build_logs_to_retain: 10
    plan:
      - get: git-repo-master
      - put: docker_image
        params:
          build: docker-repo
          tag: resource_version/version
          tag_as_latest: true

