# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTemplateEngine < Formula
  desc "Easy tool to apply Go Templates in BAU jobs"
  homepage "https://github.com/marcelocorreia/go-template-engine"
  version "7.8.0"
  license "NotSureYet"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/marcelocorreia/go-template-engine/releases/download/7.8.0/go-template-engine-7.8.0-darwin-x86_64.tar.gz"
    sha256 "0a1908fdca0efce87b588af88dc08a009216849efa8bdf0cf36710ac4ae645a1"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/marcelocorreia/go-template-engine/releases/download/7.8.0/go-template-engine-7.8.0-linux-x86_64.tar.gz"
    sha256 "07fdafda8e1a4d49d4c8a7e6f26b82c1f4903a59ea2fffbf5afac992de20e407"
  end

  def install
    bin.install "go-template-engine"
  end

  test do
    system "#{bin}/go-template-engine --version"
  end
end
