# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTemplateEngine < Formula
  desc "Easy tool to apply Go Templates in BAU jobs"
  homepage "https://github.com/marcelocorreia/go-template-engine"
  version "7.10.1"
  license "NotSureYet"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcelocorreia/go-template-engine/releases/download/7.10.1/go-template-engine-7.10.1-darwin-x86_64.tar.gz"
      sha256 "74148a04451d922a9c3c835e14c4b5fedcc36d27a6d879e8298c8ba56b2120e2"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/marcelocorreia/go-template-engine/releases/download/7.10.1/go-template-engine-7.10.1-linux-x86_64.tar.gz"
      sha256 "f9a4541b6064eff2a07f7171cf6fc63bdebeca5a30bbf586d0b79b06e5722641"
    end
  end

  def install
    bin.install "go-template-engine"
  end

  test do
    system "#{bin}/go-template-engine --version"
  end
end
