# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTemplateEngine < Formula
  desc "Easy tool to apply Go Templates in BAU jobs"
  homepage "https://github.com/marcelocorreia/go-template-engine"
  version "7.6.0"
  license "NotSureYet"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/marcelocorreia/go-template-engine/releases/download/7.6.0/go-template-engine-7.6.0-darwin-x86_64.tar.gz"
    sha256 "6254f998a0fc41a72b0bdd8ead0a5d729f5110276640fd2a40d2439efb9ca34d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/marcelocorreia/go-template-engine/releases/download/7.6.0/go-template-engine-7.6.0-linux-x86_64.tar.gz"
    sha256 "e1dda0a22e7b2424342de11b9883746b83ce0a5943cb65d1321255a88980d387"
  end

  def install
    bin.install "go-template-engine"
  end

  test do
    system "#{bin}/go-template-engine --version"
  end
end
