# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semver < Formula
  desc "Semver tool"
  homepage "https://github.com/marcelocorreia/semver"
  version "0.5.0"
  license "NotSureYet"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcelocorreia/semver/releases/download/0.5.0/semver-0.5.0-darwin-x86_64.tar.gz"
      sha256 "944a9244926008d01b97c5c1d87e81b34034ac1fa6fd53d7673db306952addad"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/marcelocorreia/semver/releases/download/0.5.0/semver-0.5.0-linux-x86_64.tar.gz"
      sha256 "05573ccbe600a82db34e4425924c44e37fad9b2516720a1519696f6d10738db0"
    end
  end

  def install
    bin.install "semver"
  end

  test do
    system "#{bin}/semver --version"
  end
end
