# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semver < Formula
  desc "Semver tool"
  homepage "https://github.com/marcelocorreia/semver"
  version "1.0.0"
  license "NotSureYet"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcelocorreia/semver/releases/download/1.0.0/semver-1.0.0-darwin-x86_64.tar.gz"
      sha256 "95d22458db70a27cf058c900b28675fbe2270c6026fe2bcebfee68f4de3820e3"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/marcelocorreia/semver/releases/download/1.0.0/semver-1.0.0-linux-x86_64.tar.gz"
      sha256 "779c7a947f61e87bc580c6034cbc99d30459c3ac843e996814bba464300c61cb"
    end
  end

  def install
    bin.install "semver"
  end

  test do
    system "#{bin}/semver --version"
  end
end
