# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semver < Formula
  desc "Semver tool"
  homepage "https://github.com/marcelocorreia/semver"
  version "0.0.1"
  license "NotSureYet"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/marcelocorreia/semver/releases/download/0.0.1/semver-0.0.1-darwin-x86_64.tar.gz"
    sha256 "ac504e2300ca8385a05f1e2ed96ac28e1230b9eea9d4b58148f4628ade3f0fdf"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/marcelocorreia/semver/releases/download/0.0.1/semver-0.0.1-linux-x86_64.tar.gz"
    sha256 "163996611f7399530a3e0f30124a109b779bc300fa45d15758208badd289f549"
  end

  def install
    bin.install "semver"
  end

  test do
    system "#{bin}/semver --version"
  end
end
